# Generated by Django 5.0.1 on 2026-01-20 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('anomaly_value', models.FloatField()),
                ('severity_score', models.FloatField(null=True)),
                ('anomaly_type', models.CharField(max_length=50, null=True)),
                ('detection_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anomaly_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiometricAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('bio_age_5_17', models.IntegerField()),
                ('bio_age_17_plus', models.IntegerField(db_column='bio_age_17_')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'biometric_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('age_0_5', models.IntegerField()),
                ('age_5_17', models.IntegerField()),
                ('age_18_greater', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': False,
            },
        ),
    ]
